image: maven:latest

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: " --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=./../.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - cd calculator-lib
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - cd calculator-lib
    - mvn $MAVEN_CLI_OPTS test